'hide empty members
'hide circle

package Libro{

    package Hoja {
        interface Comportamiento
        Rango *-d-- Celda
        Rango <|-r- Vector
        Vector <|-- Fila
        Vector <|-- Columna
        TablaDinámica *--l-- Tabla
        TablaDinámica -r-|> Comportamiento
        Tabla o-d- Rango
        Gráfico ...> Rango
        Gráfico .l..> Tabla
        Gráfico .u..> TablaDinámica
        
        Celda .r. Fórmula
        Rango .d. Fórmula
        

        class Celda as "<i><b>Celda</b></i>" {
            dirección
        }
    }
}
