hide empty members

package Hoja {
    interface Comportamiento
    Rango *-d--- Celda
    Rango <|-- Vector 
    Vector <|-- Fila
    Vector <|-- Columna
    Tabla o-d- Rango
    TablaDinámica *-d- Tabla
    TablaDinámica -r-|> Comportamiento
    Gráfico .l.> Rango
    Gráfico ..> Tabla
    Gráfico ..> TablaDinámica
}

class Celda{
    dirección
}
