hide empty members

package Libro{

    package Hoja {
        interface Comportamiento
        Rango *-d- Celda
        Rango <|-r- Vector 
        Vector <|-- Fila
        Vector <|-- Columna
        TablaDinámica *-d- Tabla
        Tabla o-d- Rango
        TablaDinámica -r-|> Comportamiento
        Gráfico ...> Rango
        Gráfico .l..> Tabla
        Gráfico .u..> TablaDinámica
    }
}


class Celda{
    dirección
}
